-- V1 is the legacy BIGINT/IDENTITY schema generated by Hibernate. It is only
-- executed for a new, empty database; V2 converts it to native UUID keys.
--
-- Existing-database baseline instructions are in ../README.md beside these
-- migrations. Never enable automatic baselining: Flyway baseline does not
-- execute or validate V1.

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username varchar(50) NOT NULL,
    password varchar(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username)
);

CREATE TABLE teams (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100) NOT NULL,
    description varchar(255),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    owner_id bigint NOT NULL,
    CONSTRAINT pk_teams PRIMARY KEY (id)
);

CREATE TABLE correspondents (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100) NOT NULL,
    notes varchar(255),
    CONSTRAINT pk_correspondents PRIMARY KEY (id),
    CONSTRAINT uq_correspondents_name UNIQUE (name)
);

CREATE TABLE document_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100) NOT NULL,
    description varchar(255),
    CONSTRAINT pk_document_types PRIMARY KEY (id),
    CONSTRAINT uq_document_types_name UNIQUE (name)
);

CREATE TABLE team_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role varchar(255) NOT NULL,
    joined_at timestamp(6) with time zone,
    CONSTRAINT pk_team_members PRIMARY KEY (id),
    CONSTRAINT uq_team_members_team_user UNIQUE (team_id, user_id),
    CONSTRAINT fk_team_members_team FOREIGN KEY (team_id) REFERENCES teams (id),
    CONSTRAINT fk_team_members_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_team_members_role CHECK (role IN ('ADMIN', 'READONLY', 'READ_WRITE'))
);

CREATE TABLE documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title varchar(255) NOT NULL,
    original_filename varchar(255) NOT NULL,
    content_type varchar(255) NOT NULL,
    file_size bigint NOT NULL,
    owner_id bigint NOT NULL,
    team_id bigint,
    status varchar(255) NOT NULL,
    ocr_content text,
    summary text,
    storage_key varchar(255),
    correspondent_id bigint,
    document_type_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT pk_documents PRIMARY KEY (id),
    CONSTRAINT fk_documents_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_documents_team FOREIGN KEY (team_id) REFERENCES teams (id),
    CONSTRAINT fk_documents_correspondent FOREIGN KEY (correspondent_id) REFERENCES correspondents (id),
    CONSTRAINT fk_documents_document_type FOREIGN KEY (document_type_id) REFERENCES document_types (id),
    CONSTRAINT ck_documents_status CHECK (
        status IN ('PENDING', 'OCR_IN_PROGRESS', 'GENAI_IN_PROGRESS', 'COMPLETED', 'FAILED')
    )
);

CREATE TABLE access_tokens (
    digest varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT pk_access_tokens PRIMARY KEY (digest),
    CONSTRAINT uq_access_tokens_user_id UNIQUE (user_id),
    CONSTRAINT fk_access_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);
